(in-package :yaml-eval)

(defvar *gram4* (load-yaml-grammar "yaml-grammar.scm"))

(defun read-file-string (path)
  (with-open-file (s path :external-format :utf-8)
    (let* ((len (file-length s))
           (data (make-string len)))
      (let ((n (read-sequence data s))) (subseq data 0 n)))))

(defun replace-char-in-string (str old-char new-str)
  (with-output-to-string (out)
    (loop for c across str do
      (if (char= c old-char) (write-string new-str out) (write-char c out)))))

(defun decode-yaml-special-chars (text)
  (let ((r text))
    (setf r (replace-char-in-string r (code-char #x2423) " "))
    (setf r (replace-char-in-string r (code-char #x21B5) ""))
    (setf r (replace-char-in-string r (code-char #x2192) (string #\Tab)))
    (setf r (replace-char-in-string r (code-char #x2190) (string #\Return)))
    (setf r (replace-char-in-string r (code-char #x21D4) (string (code-char #xFEFF))))
    (setf r (replace-char-in-string r (code-char #x220E) ""))
    (setf r (replace-char-in-string r (code-char #x2014) ""))
    (setf r (replace-char-in-string r (code-char #x00BB) (string #\Tab)))
    r))

(defun extract-yaml-blocks (text)
  (let ((results nil)
        (lines (with-input-from-string (s text)
                 (loop for line = (read-line s nil nil) while line collect line)))
        (cur-name "") (cur-yaml nil) (cur-error nil) (cur-fail nil)
        (in-yaml nil) (yaml-indent 0))
    (dolist (line lines)
      (let ((trimmed (string-left-trim '(#\Space) line))
            (leading (loop for c across line while (char= c #\Space) count t)))
        (cond
          ((and (>= (length trimmed) 7)
                (string= "- name:" (subseq trimmed 0 (min 7 (length trimmed)))))
           (when (and (> (length cur-name) 0) cur-yaml)
             (push (list cur-name
                         (decode-yaml-special-chars (format nil "~{~a~%~}" (nreverse cur-yaml)))
                         cur-error cur-fail) results))
           (setf cur-name (string-trim '(#\Space) (subseq trimmed 7))
                 cur-yaml nil cur-error nil cur-fail nil in-yaml nil yaml-indent 0))
          ((and (search "tags:" line) (search "error" line)) (setf cur-error t))
          ((and (>= (length trimmed) 10) (search "fail: true" trimmed)) (setf cur-fail t))
          ((and (not in-yaml) (or (string= trimmed "yaml: |") (string= trimmed "yaml: |+")))
           (setf in-yaml t yaml-indent 0))
          (in-yaml
           (cond
             ((string= trimmed "") (when cur-yaml (push "" cur-yaml)))
             ((and (> yaml-indent 0) (< leading yaml-indent)) (setf in-yaml nil))
             ((= yaml-indent 0) (setf yaml-indent leading)
              (push (if (>= (length line) leading) (subseq line leading) "") cur-yaml))
             (t (push (if (>= (length line) yaml-indent) (subseq line yaml-indent) line) cur-yaml)))))))
    (when (and (> (length cur-name) 0) cur-yaml)
      (push (list cur-name (decode-yaml-special-chars (format nil "~{~a~%~}" (nreverse cur-yaml)))
                  cur-error cur-fail) results))
    (nreverse results)))

(defun only-whitespace-p (str start)
  "Check if STR from START to end contains only whitespace/newlines."
  (loop for i from start below (length str)
        always (member (char str i) '(#\Space #\Tab #\Newline #\Return))))

(defun run-test-suite (dir)
  (let ((files (sort (directory (merge-pathnames "*.yaml" (pathname dir)))
                     #'string< :key #'namestring))
        (pass 0) (fail 0) (known-fail 0) (correct-reject 0) (miss 0) (skip 0) (total 0)
        (failures nil))
    (dolist (file files)
      (let ((tests (handler-case (extract-yaml-blocks (read-file-string (namestring file)))
                     (error () nil))))
        (dolist (test tests)
          (incf total)
          (let ((name (first test)) (yaml (second test))
                (is-error (third test)) (is-fail (fourth test)))
            (if (or (null yaml) (string= yaml "") (string= yaml (format nil "~%")))
                (incf skip)
                (let ((result (handler-case
                                  (let ((*memo* (make-hash-table :test 'equal)))
                                    (multiple-value-bind (ok val pos ast)
                                        (yaml-parse *gram4* yaml)
                                      (declare (ignore val))
                                      (if (and ok ast 
                                               (or (= pos (length yaml))
                                                   (only-whitespace-p yaml pos)))
                                          :parsed
                                          :rejected)))
                                (error () :error))))
                  (cond
                    ((and (not is-error) (eq result :parsed)) (incf pass))
                    ((and (not is-error) is-fail (member result '(:rejected :error))) (incf known-fail))
                    ((and (not is-error) (member result '(:rejected :error)))
                     (incf fail) (push (list (file-namestring file) name) failures))
                    ((and is-error (member result '(:rejected :error))) (incf correct-reject))
                    ((and is-error (eq result :parsed)) (incf miss)))))))))
    (let ((testable (+ pass fail)))
      (format t "~%============================================================~%")
      (format t " YAML Test Suite Results~%")
      (format t "============================================================~%")
      (format t "~%  Total:              ~D~%" total)
      (format t "  Passed:             ~D~%" pass)
      (format t "  Failed:             ~D  (real failures)~%" fail)
      (format t "  Known-fail:         ~D  (test marked fail:true)~%" known-fail)
      (format t "  Correct reject:     ~D  (error tests we rejected)~%" correct-reject)
      (format t "  Missed error:       ~D  (error tests we accepted)~%" miss)
      (format t "~%  Pass rate:          ~,1F%  (~D/~D non-error, non-fail tests)~%"
              (if (> testable 0) (* 100.0 (/ pass testable)) 0.0) pass testable)
      (format t "~%  Total correct:      ~D/~D  (~,1F%)~%"
              (+ pass correct-reject) (- total skip known-fail)
              (* 100.0 (/ (+ pass correct-reject) (max 1 (- total skip known-fail)))))
      (when failures
        (format t "~%  --- REAL FAILURES ---~%")
        (dolist (f (reverse failures))
          (format t "    ~A: ~A~%" (first f) (second f))))
      (format t "~%============================================================~%"))))

(run-test-suite "yaml-tests/src/")
